### PR TITLE
Update llvm_version.txt

### PR DESCRIPTION
**Pull request by Yun-Fly**
Update LLVM version to cover latest upstream patch regarding to consumer fusion for `tensor.pack`. Otherwise, [GC PR](https://github.com/intel/graph-compiler/pull/280) will fail in GPU with IMEX.

### CODE REVIEW

**Comment by Yun-Fly** [comment]
This commit id is aligned with GC. @Menooker @ZhennanQin @kurapov-peter @dchigarev, please help to review.

**Review by dchigarev — APPROVED** [review]
does the IMEX build pass?

**Comment by dchigarev** [comment]
at least the IMEX patches doesn't work for me:
```
~/llvm$ git apply ../mlir-extensions/build_tools/patches/*
error: patch failed: mlir/include/mlir/Dialect/SPIRV/IR/SPIRVBase.td:4189
error: mlir/include/mlir/Dialect/SPIRV/IR/SPIRVBase.td: patch does not apply
```
we don't need them anymore?

p.s. it seems that we need these patches, without them the IMEX build fails with numerous errors

**Comment by Yun-Fly** [comment]
> at least the IMEX patches doesn't work for me:
> 
> ```
> ~/llvm$ git apply ../mlir-extensions/build_tools/patches/*
> error: patch failed: mlir/include/mlir/Dialect/SPIRV/IR/SPIRVBase.td:4189
> error: mlir/include/mlir/Dialect/SPIRV/IR/SPIRVBase.td: patch does not apply
> ```
> 
> we don't need them anymore?
> 
> p.s. it seems that we need these patches, without them the IMEX build fails with numerous errors

It is caused by [0009-SPIR-V-Enable-native-bf16-support-in-SPIR-V-dialect.patch](https://github.com/Menooker/mlir-extensions/blob/main/build_tools/patches/0009-SPIR-V-Enable-native-bf16-support-in-SPIR-V-dialect.patch), which has conflict with the latest LLVM.

**Comment by dchigarev** [comment]
@Yun-Fly are you working on fixing the incompatibilities, or should someone else take the lead?

**Comment by Yun-Fly** [comment]
> @Yun-Fly are you working on fixing the incompatibilities, or should someone else take the lead?

I am working on something else with higher priority recently. I would be very appreciated If someone can help to take this:)

**Comment by dchigarev** [comment]
Updated IMEX to the latest LLVM in this PR (#4)

**Comment by Yun-Fly** [comment]
> Updated IMEX to the latest LLVM in this PR (#4)

Awesome! Thanks a lot for contributing that!

**Pull request closed without merging**
